[project]
name = "textual-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mongoengine>=0.29.1",
    "textual-forms",
]

[tool.uv.sources]
textual-forms = { path = "../textual-forms", editable = true }

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
